tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: google_map_iframe
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Google Map Iframe'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
                - url
