tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: description
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
                - h1
                - h4
                - h5
                - h6
                - underline
                - strikethrough
                - small
                - superscript
                - subscript
                - alignleft
                - aligncenter
                - alignright
                - alignjustify
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              container: local
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Description
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - sometimes
          -
            handle: images
            field:
              max_files: 1
              min_files: 1
              mode: grid
              container: local
              folder: projectimages
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Images
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
                - image
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: project_category
            field:
              type: terms
              taxonomies:
                - project_category
              display: 'Project Category'
              mode: select
title: Project
